Add clusterrole and clusterrolebinding to enable operator lesson
prgcont/k8s-do pull request #4
Opened 2018-10-08 13:28 UTC by jwerak

2018-10-15 13:17 UTC, rwngwn requested changes

2018-10-15 13:17 UTC, dbecvarik commented on hosts
> +master ansible_host=206.189.0.35
are you sure we want to commit this? :)

2018-10-16 06:44 UTC, jwerak commented on hosts
> +master ansible_host=206.189.0.35
not really

2018-10-16 18:15 UTC, rwngwn approved these changes

2018-10-16 18:15 UTC, merged